--------------------------------------------------------
-- Archivo creado  - viernes-octubre-18-2019   
--------------------------------------------------------
-- No se ha podido presentar el DDL SEQUENCE para el objeto RRENDON.ISEQ$$_74791 mientras que DBMS_METADATA intenta utilizar el generador interno.
CREATE SEQUENCE ISEQ$$_74791 INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20
-- No se ha podido presentar el DDL SEQUENCE para el objeto RRENDON.ISEQ$$_74794 mientras que DBMS_METADATA intenta utilizar el generador interno.
CREATE SEQUENCE ISEQ$$_74794 INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20
-- No se ha podido presentar el DDL SEQUENCE para el objeto RRENDON.ISEQ$$_74797 mientras que DBMS_METADATA intenta utilizar el generador interno.
CREATE SEQUENCE ISEQ$$_74797 INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20
-- No se ha podido presentar el DDL SEQUENCE para el objeto RRENDON.ISEQ$$_74800 mientras que DBMS_METADATA intenta utilizar el generador interno.
CREATE SEQUENCE ISEQ$$_74800 INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20
-- No se ha podido presentar el DDL SEQUENCE para el objeto RRENDON.ISEQ$$_74803 mientras que DBMS_METADATA intenta utilizar el generador interno.
CREATE SEQUENCE ISEQ$$_74803 INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20
-- No se ha podido presentar el DDL SEQUENCE para el objeto RRENDON.ISEQ$$_74806 mientras que DBMS_METADATA intenta utilizar el generador interno.
CREATE SEQUENCE ISEQ$$_74806 INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20
-- No se ha podido presentar el DDL SEQUENCE para el objeto RRENDON.ISEQ$$_74809 mientras que DBMS_METADATA intenta utilizar el generador interno.
CREATE SEQUENCE ISEQ$$_74809 INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20
--------------------------------------------------------
--  DDL for Table BARRIOS
--------------------------------------------------------

  CREATE TABLE "RRENDON"."BARRIOS" 
   (	"ID" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(255 BYTE), 
	"COMUNA_ID" NUMBER(22,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MID_TERM" ;
--------------------------------------------------------
--  DDL for Table COMUNAS
--------------------------------------------------------

  CREATE TABLE "RRENDON"."COMUNAS" 
   (	"ID" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(255 BYTE), 
	"TIPO_COMUNA_ID" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MID_TERM" ;
--------------------------------------------------------
--  DDL for Table ESTADOS_PRESENTADORES
--------------------------------------------------------

  CREATE TABLE "RRENDON"."ESTADOS_PRESENTADORES" 
   (	"ID" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MID_TERM" ;
--------------------------------------------------------
--  DDL for Table MODALIDADES
--------------------------------------------------------

  CREATE TABLE "RRENDON"."MODALIDADES" 
   (	"ID" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MID_TERM" ;
--------------------------------------------------------
--  DDL for Table PRESENTADORES
--------------------------------------------------------

  CREATE TABLE "RRENDON"."PRESENTADORES" 
   (	"ID" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(255 BYTE), 
	"FECHA_CONTRATACION" DATE, 
	"VALOR_CONTRATO" NUMBER(*,0), 
	"ESTADO_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MID_TERM" ;
--------------------------------------------------------
--  DDL for Table SEDES
--------------------------------------------------------

  CREATE TABLE "RRENDON"."SEDES" 
   (	"ID" NUMBER(*,0), 
	"SEDE" VARCHAR2(255 BYTE), 
	"TELEFONO" VARCHAR2(255 BYTE), 
	"DIRECCION" VARCHAR2(255 BYTE), 
	"CUPOS_DISPUESTOS" NUMBER(*,0), 
	"BARRIO_ID" NUMBER(*,0), 
	"MODALIDAD_ID" NUMBER(*,0), 
	"PRESENTADOR_ID" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MID_TERM" ;
--------------------------------------------------------
--  DDL for Table TIPO_COMUNAS
--------------------------------------------------------

  CREATE TABLE "RRENDON"."TIPO_COMUNAS" 
   (	"ID" NUMBER(*,0), 
	"TIPO" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MID_TERM" ;
REM INSERTING into RRENDON.BARRIOS
SET DEFINE OFF;
REM INSERTING into RRENDON.COMUNAS
SET DEFINE OFF;
REM INSERTING into RRENDON.ESTADOS_PRESENTADORES
SET DEFINE OFF;
Insert into RRENDON.ESTADOS_PRESENTADORES (ID,NOMBRE) values ('40','ACTIVO');
Insert into RRENDON.ESTADOS_PRESENTADORES (ID,NOMBRE) values ('41','INACTIVO');
Insert into RRENDON.ESTADOS_PRESENTADORES (ID,NOMBRE) values ('42','SUSPENDIDO');
Insert into RRENDON.ESTADOS_PRESENTADORES (ID,NOMBRE) values ('43','BAJO INVESTIGACION');
REM INSERTING into RRENDON.MODALIDADES
SET DEFINE OFF;
REM INSERTING into RRENDON.PRESENTADORES
SET DEFINE OFF;
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('501','ALMALEGRE - FUNDACION EDUCATIVA',to_date('03/12/16','DD/MM/RR'),'168435044893','41');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('502','AMIGOS DE LOS NINOS - ASOCIACION',to_date('27/11/17','DD/MM/RR'),'199014954237','41');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('503','AUTONOMA DE LAS AMERICAS - FUNDACION UNIVERSITARIA',to_date('16/08/18','DD/MM/RR'),'188011526339','43');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('504','CALMECAC - CORPORACION',to_date('09/11/16','DD/MM/RR'),'108523403540','41');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('505','CARITAS ARQUIDIOCESANA DE MEDELLIN  PASTORAL SOCIAL',to_date('04/09/17','DD/MM/RR'),'95069881375','41');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('506','CARLA CRISTINA - FUNDACION EDUCADORA INFANTIL',to_date('22/02/16','DD/MM/RR'),'181924742476','41');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('507','CARULLA - FUNDACION',to_date('25/02/19','DD/MM/RR'),'144017085587','40');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('508','CASA DEL CAMINO - CORPORACION HOGAR INFANTIL',to_date('24/01/16','DD/MM/RR'),'73899091530','42');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('509','COMFAMA - CAJA DE COMPENSACION FAMILIAR DE ANTIOQUIA ',to_date('17/08/17','DD/MM/RR'),'54391415142','40');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('510','COMFENALCO - CAJA DE COMPENSACION FAMILAR ',to_date('06/05/16','DD/MM/RR'),'113106182591','43');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('511','COMUNIQUEMONOS - CORPORACION',to_date('06/03/19','DD/MM/RR'),'65064851962','40');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('512','COOMEI  - COOPERATIVA MULTIACTIVA PARA LA EDUCACION INTEGRAL',to_date('26/04/19','DD/MM/RR'),'162955915680','43');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('513','COOMULSAP - COOPERATIVA MULTIACTIVA DE SAN ANTONIO DE PRADO ',to_date('27/11/17','DD/MM/RR'),'90958963948','41');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('514','CORINGE - CORPORACION EDUCATIVA NUEVA GENTE',to_date('09/10/17','DD/MM/RR'),'176693717607','42');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('515','CORMAUN - CORPORACION MUJERES AUTONOMAS UNIDAS',to_date('03/02/16','DD/MM/RR'),'172405717470','43');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('516','CREANDO FUTURO - CORPORACION',to_date('04/09/16','DD/MM/RR'),'98005090471','41');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('517','DEJANDO HUELLA - FUNDACION',to_date('01/01/18','DD/MM/RR'),'145121005625','41');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('518','EDUCACION SIN FRONTERAS - CORPORACION',to_date('10/06/19','DD/MM/RR'),'81384166273','41');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('519','EMANUEL - FUNDACION CENTRO DE ATENCION INTEGRAL ',to_date('19/09/17','DD/MM/RR'),'156142813798','43');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('520','ESCUELA EMPRESARIAL DE EDUCACION - CORPORACION',to_date('14/01/19','DD/MM/RR'),'70857012610','43');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('521','FAN - FUNDACION DE ATENCION A LA NINEZ',to_date('17/12/18','DD/MM/RR'),'187778610656','41');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('522','GENTE UNIDA - FUNDACION',to_date('16/08/16','DD/MM/RR'),'155000549281','41');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('523','GOTA DE LECHE - JARDIN SALA CUNAS',to_date('19/03/17','DD/MM/RR'),'75904404374','40');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('524','GUAYAQUIL - FUNDACION PARA LA PROMOCION HUMANA',to_date('17/06/19','DD/MM/RR'),'192426683056','43');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('525','HERMANAS MISIONERAS DE LA COMUNIDAD CRISTIANA ',to_date('27/02/16','DD/MM/RR'),'94915623279','40');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('526','HOGARES BAMBI - FUNDACION AYUDA A LA INFANCIA',to_date('20/05/16','DD/MM/RR'),'103037340125','43');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('527','HUELLITAS DE ANGELES - JARDIN INFANTIL-GLORIA DEL SOCORRO MOLINA RAMIR',to_date('02/05/18','DD/MM/RR'),'172145517042','43');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('528','JESUS AMIGO - CORPORACION EDUCATIVA Y CULTURAL',to_date('17/05/16','DD/MM/RR'),'71461088009','41');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('529','LA LIBERTAD - CORPORACION PARA LA ATENCION A LA PRIMERA INFANCIA',to_date('10/01/16','DD/MM/RR'),'186959755219','40');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('530','LAS COMETAS - CORPORACION',to_date('15/06/16','DD/MM/RR'),'105671307149','43');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('531','LAS GOLONDRINAS - FUNDACION',to_date('22/06/16','DD/MM/RR'),'88530353870','43');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('532','LATINA - CORPORACION',to_date('16/09/18','DD/MM/RR'),'106156150645','41');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('533','LAZOS EDUCATIVOS - FUNDACION',to_date('09/02/18','DD/MM/RR'),'129126846944','43');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('534','LUIS FERNANDO VIVE - FUNDACION',to_date('09/09/18','DD/MM/RR'),'74169562719','40');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('535','MADRID CAMPESTRE - FUNDACION',to_date('12/12/17','DD/MM/RR'),'90862286252','42');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('536','METROSALUD',to_date('17/06/18','DD/MM/RR'),'173902541960','41');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('537','MUNDO MEJOR - FUNDACION',to_date('08/04/16','DD/MM/RR'),'196204708451','43');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('538','PALABRA PAN Y PEZ - FUNDACION',to_date('21/03/18','DD/MM/RR'),'100217093907','40');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('539','PAN - COMITE PRIVADO DE ASISTENCIA A LA NINEZ ',to_date('20/08/16','DD/MM/RR'),'155865480706','43');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('540','POR UN NUEVO SANTANDER - CORPORACION',to_date('28/01/19','DD/MM/RR'),'88110016401','41');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('541','POSITIVOS POR LA VIDA - FUNDACION',to_date('29/04/19','DD/MM/RR'),'151591059647','40');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('542','PRESENCIA COLOMBO SUIZA - CORPORACION',to_date('23/05/19','DD/MM/RR'),'106951788015','40');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('543','RED COMUNITARIA - CORPORACION DE DESARROLLO HUMANO Y SOCIAL',to_date('15/01/19','DD/MM/RR'),'170334724976','40');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('544','SAN JUAN EUDES - FUNDACION EDUCATIVA',to_date('13/01/17','DD/MM/RR'),'109517091484','42');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('545','SENDEROS DE AMOR Y PAZ - FUNDACION',to_date('18/05/17','DD/MM/RR'),'163373982744','43');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('546','SER Y HACER - CORPORACION EDUCATIVA',to_date('21/04/16','DD/MM/RR'),'58095016968','43');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('547','SIMON BOLIVAR - CORPORACION EDUCATIVA Y CULTURAL',to_date('11/09/16','DD/MM/RR'),'66897656536','43');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('548','UTAIPI - UNION TEMPORAL ATENCION INTEGRAL A LA PRIMERA INFANCIA',to_date('12/08/16','DD/MM/RR'),'71674294053','40');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('549','VIDA AMBIENTAL - CORPORACION',to_date('05/07/18','DD/MM/RR'),'177211518358','42');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('550','VIVIENDO JUNTOS - CORPORACION',to_date('28/10/18','DD/MM/RR'),'199530616718','40');
Insert into RRENDON.PRESENTADORES (ID,NOMBRE,FECHA_CONTRATACION,VALOR_CONTRATO,ESTADO_ID) values ('551','XIMENA RICO LLANO - FUNDACION',to_date('10/10/18','DD/MM/RR'),'53730061821','41');
REM INSERTING into RRENDON.SEDES
SET DEFINE OFF;
REM INSERTING into RRENDON.TIPO_COMUNAS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index BARRIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RRENDON"."BARRIOS_PK" ON "RRENDON"."BARRIOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "MID_TERM" ;
--------------------------------------------------------
--  DDL for Index COMUNAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RRENDON"."COMUNAS_PK" ON "RRENDON"."COMUNAS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "MID_TERM" ;
--------------------------------------------------------
--  DDL for Index ESTADOS_PRESENTADORES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RRENDON"."ESTADOS_PRESENTADORES_PK" ON "RRENDON"."ESTADOS_PRESENTADORES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MID_TERM" ;
--------------------------------------------------------
--  DDL for Index MODALIDADES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RRENDON"."MODALIDADES_PK" ON "RRENDON"."MODALIDADES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "MID_TERM" ;
--------------------------------------------------------
--  DDL for Index PRESENTADORES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RRENDON"."PRESENTADORES_PK" ON "RRENDON"."PRESENTADORES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MID_TERM" ;
--------------------------------------------------------
--  DDL for Index SEDES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RRENDON"."SEDES_PK" ON "RRENDON"."SEDES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "MID_TERM" ;
--------------------------------------------------------
--  DDL for Index T_COMUNAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RRENDON"."T_COMUNAS_PK" ON "RRENDON"."TIPO_COMUNAS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "MID_TERM" ;
--------------------------------------------------------
--  Constraints for Table BARRIOS
--------------------------------------------------------

  ALTER TABLE "RRENDON"."BARRIOS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "RRENDON"."BARRIOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "RRENDON"."BARRIOS" MODIFY ("COMUNA_ID" NOT NULL ENABLE);
  ALTER TABLE "RRENDON"."BARRIOS" ADD CONSTRAINT "BARRIOS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "MID_TERM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMUNAS
--------------------------------------------------------

  ALTER TABLE "RRENDON"."COMUNAS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "RRENDON"."COMUNAS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "RRENDON"."COMUNAS" ADD CONSTRAINT "COMUNAS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "MID_TERM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ESTADOS_PRESENTADORES
--------------------------------------------------------

  ALTER TABLE "RRENDON"."ESTADOS_PRESENTADORES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "RRENDON"."ESTADOS_PRESENTADORES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "RRENDON"."ESTADOS_PRESENTADORES" ADD CONSTRAINT "ESTADOS_PRESENTADORES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MID_TERM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MODALIDADES
--------------------------------------------------------

  ALTER TABLE "RRENDON"."MODALIDADES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "RRENDON"."MODALIDADES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "RRENDON"."MODALIDADES" ADD CONSTRAINT "MODALIDADES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "MID_TERM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRESENTADORES
--------------------------------------------------------

  ALTER TABLE "RRENDON"."PRESENTADORES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "RRENDON"."PRESENTADORES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "RRENDON"."PRESENTADORES" MODIFY ("FECHA_CONTRATACION" NOT NULL ENABLE);
  ALTER TABLE "RRENDON"."PRESENTADORES" MODIFY ("VALOR_CONTRATO" NOT NULL ENABLE);
  ALTER TABLE "RRENDON"."PRESENTADORES" ADD CONSTRAINT "PRESENTADORES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MID_TERM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SEDES
--------------------------------------------------------

  ALTER TABLE "RRENDON"."SEDES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "RRENDON"."SEDES" MODIFY ("SEDE" NOT NULL ENABLE);
  ALTER TABLE "RRENDON"."SEDES" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "RRENDON"."SEDES" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "RRENDON"."SEDES" MODIFY ("CUPOS_DISPUESTOS" NOT NULL ENABLE);
  ALTER TABLE "RRENDON"."SEDES" MODIFY ("BARRIO_ID" NOT NULL ENABLE);
  ALTER TABLE "RRENDON"."SEDES" MODIFY ("MODALIDAD_ID" NOT NULL ENABLE);
  ALTER TABLE "RRENDON"."SEDES" MODIFY ("PRESENTADOR_ID" NOT NULL ENABLE);
  ALTER TABLE "RRENDON"."SEDES" ADD CONSTRAINT "SEDES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "MID_TERM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TIPO_COMUNAS
--------------------------------------------------------

  ALTER TABLE "RRENDON"."TIPO_COMUNAS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "RRENDON"."TIPO_COMUNAS" MODIFY ("TIPO" NOT NULL ENABLE);
  ALTER TABLE "RRENDON"."TIPO_COMUNAS" ADD CONSTRAINT "T_COMUNAS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "MID_TERM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BARRIOS
--------------------------------------------------------

  ALTER TABLE "RRENDON"."BARRIOS" ADD FOREIGN KEY ("COMUNA_ID")
	  REFERENCES "RRENDON"."COMUNAS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMUNAS
--------------------------------------------------------

  ALTER TABLE "RRENDON"."COMUNAS" ADD FOREIGN KEY ("TIPO_COMUNA_ID")
	  REFERENCES "RRENDON"."TIPO_COMUNAS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRESENTADORES
--------------------------------------------------------

  ALTER TABLE "RRENDON"."PRESENTADORES" ADD FOREIGN KEY ("ESTADO_ID")
	  REFERENCES "RRENDON"."ESTADOS_PRESENTADORES" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SEDES
--------------------------------------------------------

  ALTER TABLE "RRENDON"."SEDES" ADD FOREIGN KEY ("BARRIO_ID")
	  REFERENCES "RRENDON"."BARRIOS" ("ID") ENABLE;
  ALTER TABLE "RRENDON"."SEDES" ADD FOREIGN KEY ("MODALIDAD_ID")
	  REFERENCES "RRENDON"."MODALIDADES" ("ID") ENABLE;
  ALTER TABLE "RRENDON"."SEDES" ADD FOREIGN KEY ("PRESENTADOR_ID")
	  REFERENCES "RRENDON"."PRESENTADORES" ("ID") ENABLE;
