ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE; 


CREATE TABLESPACE mid_term   
DATAFILE 'parcial.DBF' 
SIZE 50M  

CREATE PROFILE parcial LIMIT  
    PASSWORD_LIFE_TIME 100 
    SESSIONS_PER_USER 1 
    IDLE_TIME 10
    FAILED_LOGIN_ATTEMPTS 5;    
    

 
 CREATE USER RRENDON
IDENTIFIED BY rrendon
DEFAULT TABLESPACE mid_term;

CREATE USER RONALDR
IDENTIFIED BY rrendon
DEFAULT TABLESPACE mid_term
PROFILE PARCIAL;


CREATE ROLE MINI_DBA NOT IDENTIFIED

GRANT CREATE TABLE to MINI_DBA;
GRANT CREATE VIEW to MINI_DBA;


CREATE ROLE STUDENT NOT IDENTIFIED

GRANT CREATE SESSION TO STUDENT

GRANT MINI_DBA TO RRENDON


CREATE TABLE BARRIOS(
ID NUMERIC  NOT NULL, 
NOMBRE VARCHAR(255) NOT NULL,
COMUNA_ID NUMBER(22,0) NOT NULL,
CONSTRAINT BARRIOS_PK PRIMARY KEY (ID),

FOREIGN KEY (COMUNA_ID) REFERENCES COMUNAS(ID))  

TABLESPACE mid_term; 

CREATE TABLE COMUNAS(
ID NUMERIC  NOT NULL, 
NOMBRE VARCHAR(255) NOT NULL,
TIPO_COMUNA_ID NUMERIC,
CONSTRAINT COMUNAS_PK PRIMARY KEY (ID),

FOREIGN KEY (TIPO_COMUNA_ID) REFERENCES TIPO_COMUNAS(ID)
)

TABLESPACE mid_term; 


CREATE TABLE TIPO_COMUNAS(
ID NUMERIC  NOT NULL, 
TIPO VARCHAR(255) NOT NULL,
CONSTRAINT T_COMUNAS_PK PRIMARY KEY (ID))

TABLESPACE mid_term; 


CREATE TABLE ESTADOS_PRESENTADORES(
ID NUMERIC  NOT NULL, 
NOMBRE VARCHAR(255) NOT NULL,
 CONSTRAINT ESTADOS_PRESENTADORES_PK PRIMARY KEY (ID))

TABLESPACE mid_term; 

CREATE TABLE PRESENTADORES(
ID NUMERIC  NOT NULL, 
NOMBRE VARCHAR(255) NOT NULL,
FECHA_CONTRATACION DATE NOT NULL,
VALOR_CONTRATO NUMERIC NOT NULL,
ESTADO_ID NUMERIC,
CONSTRAINT PRESENTADORES_PK PRIMARY KEY (ID),
FOREIGN KEY (ESTADO_ID) REFERENCES ESTADOS_PRESENTADORES (ID)
)
TABLESPACE mid_term; 


CREATE TABLE MODALIDADES(
ID NUMERIC  NOT NULL, 
NOMBRE VARCHAR(255) NOT NULL,
CONSTRAINT MODALIDADES_PK PRIMARY KEY (ID))


TABLESPACE mid_term; 


CREATE TABLE SEDES(
ID NUMERIC NOT NULL, 
SEDE VARCHAR(255) NOT NULL,
TELEFONO VARCHAR(255) NOT NULL,
DIRECCION VARCHAR(255) NOT NULL,
CUPOS_DISPUESTOS NUMERIC NOT NULL,
BARRIO_ID NUMERIC NOT NULL,
MODALIDAD_ID NUMERIC NOT NULL,
PRESENTADOR_ID NUMERIC NOT NULL,
CONSTRAINT SEDES_PK PRIMARY KEY (ID),

FOREIGN KEY (BARRIO_ID) REFERENCES BARRIOS (ID),
FOREIGN KEY (MODALIDAD_ID) REFERENCES MODALIDADES (ID),
FOREIGN KEY (PRESENTADOR_ID) REFERENCES PRESENTADORES (ID)
)
TABLESPACE mid_term; 






